use failure::Error;

fn main() -> Result<(),Error>{
    println!("Hello, world!");
    Ok(())
}
